### PR TITLE
Ci fix

### PR DESCRIPTION
**Pull request by yoni206**
Attempting a fix suggested by @makaimann (thanks Makai!). Let's see if CI passes now.

### CODE REVIEW

**Comment by yoni206** [comment]
Does not seem to work:
https://github.com/stanford-centaur/smt-switch/actions/runs/3327034293/jobs/5501375039

**Comment by lonsing** [comment]
Hi @yoni206 and @makaimann, there was a failure in the Pono CI flow on macOS which seems to be similar. I am not sure whether the fix applied to Pono would also be applicable to smt-switch, but maybe it's worth trying: https://github.com/upscale-project/pono/pull/302

**Comment by yoni206** [comment]
Thanks Florian! I've tried adding these [04e7864](https://github.com/stanford-centaur/smt-switch/pull/310/commits/04e7864b80c872f16df3264ffe32e457682209a1) 
but now for some reason the CI claims to have no jobs to run.
image

**Comment by yoni206** [comment]
Closing as @makaimann 's PR #312 is better.

**Pull request closed without merging**
