### PR TITLE
Build CVC5 using $(nproc) threads

### PR DESCRIPTION
**Pull request by georgerennie**
This works on Darwin or Linux in line with setup-bitwuzla.sh and setup-btor.sh

### CODE REVIEW

**Comment by yoni206** [comment]
Thanks for this PR and sorry for the late reply. It looks good to me and I tested it locally. Once CI passes I'll approve and merge. @makaimann FYI.

**Comment by yoni206** [comment]
@makaimann checks fail here — is this related to the issue on CI that you are fixing?

**Comment by makaimann** [comment]
https://github.com/stanford-centaur/smt-switch/pull/298 made it so cvc5 is built in CI. If you merge master into this branch, it should pass. Would be good to check though, I’ve had issues with parallel builds in CI before.

Thanks for the PR!

**Comment by yoni206** [comment]
@georgerennie -- would it be possible for you to merge current master into your branch and push, so that the PR is synced with current master? This will allow us to check CI (which is now fixed on master).

**Review by yoni206 — APPROVED** [review]

**Pull request merged**
