### PR TITLE
:bug: deps path fixed

### PR DESCRIPTION
**Pull request by Moorvan**
When building static library of smt-switch with bitwuzla, it didn't work with this version because of this little bug.

### CODE REVIEW

**Review by yoni206 — COMMENTED** [review]
LGTM, and thanks for this!
I am a bit hesitant to promote to a newer commits of solvers, but, if CI passes then I think it is fine. @makaimann do you agree?

**Comment by yoni206** [comment]
@Moorvan -- would it be possible for you to merge current master into your branch and push, so that the PR is synced with current master? This will allow us to check CI (which is now fixed on master).

**Comment by makaimann** [comment]
> I am a bit hesitant to promote to a newer commits of solvers, but, if CI passes then I think it is fine. @makaimann do you agree?

Sorry for the slow response. I agree that as long as CI passes then it's good to go. There is risk of introducing issues of course, but it's also best to keep up to date. If it's not caught by CI, then we can add a new tests when/if issues show up.

**Comment by Moorvan** [comment]
Okay, I've done it.

> @Moorvan -- would it be possible for you to merge current master into your branch and push, so that the PR is synced with current master? This will allow us to check CI (which is now fixed on master).

**Review by yoni206 — APPROVED** [review]

**Pull request merged**
